### ISSUE TITLE
review UCR document dependency on assets from dokie.li

### ISSUE THREAD

**Issue by elf-pavlik** [solid/notifications-panel#36]
Capturing unresolved conversation from PR https://github.com/solid/notifications-panel/pull/32#discussion_r737445567

TL;DR

>> The document will work (human- and machine-readable) even if recipient is unable to access or use the CSS or JavaScript.

> In that case, consider
>```html
>   <script src="https://dokie.li/scripts/dokieli.js" async></script>
>```
>and, for lack of `defer`/`async` on stylesheets, for the `dokieli.js` to insert `https://dokie.li/media/css/dokieli.css` instead.

**Comment by elf-pavlik** [comment]
@csarven this was possibly causing an issue today when I was trying to load https://solid.github.io/notifications/protocol

**Comment by elf-pavlik** [comment]
Picking up the conversation from https://github.com/solid/notifications/issues/44

@csarven could you please try in 3-5 sentences to explain the reason for including that 3.2MB script, which seems to include a lot of deprecated npm packages and brings code with `45 vulnerabilities (35 moderate, 10 high)` into various spec documents? Notifications Protocol spec can be read perfectly fine without that script so what is the actual purpose of including it?

**Comment by VirginiaBalseiro** [comment]
Hi! Just wanted to mention, with my latest PR (https://github.com/linkeddata/dokieli/pull/312) which was merged today, dokieli has now 0 vulnerabilities.

**Comment by csarven** [comment]
Virginia++ !

I've apparently pushed the non-minified script by mistake.. and with the improvements from PR above, the script is now 1.24 MB.

Editor's decision. Dogfooding.

Closing issue as per https://github.com/solid/notifications-panel/commit/22fa9ac26a6ad2e689775d4accb4b9fc60dd4e9c .
